#server
server:
  port: 8804
#---------短信验证码--------------------
msg:
  validate-path: pvalidate #手机短信验证码认证请求的路径（未启用）
  send-path: send #手机短信验证码认证请求的路径
  #消防所
#  appId: 1400063133
#  appKey: 37c7d27d8a4c6d5231eb68003ef09d1e
#  signId: 35509
#  templId: 77405
  #消防协会
  appId: 1400156787
  appKey: 37a3ead5782373b2435a4aad3a85c5de
  signId: 176690
  templId: 218933

#---------邮箱验证码--------------------
mail:
  from: committee@cfpa.cn  #发送邮箱
  subject: 展会邮箱验证码 #邮箱标题
  time: 1小时            #时效
  system-name: 第十八届中国国际消防展展商系统  #系统名称
  team-name: 第十八届中国国际消防展组委会 #团队名称
  text:
#---------英文邮箱验证码--------------------
mailEng:
  from: committee@cfpa.cn  #发送邮箱
  subject: China Fire 2019 Verification  #邮箱标题
  time: 1 hour            #时效
  system-name: China Fire 2019 #系统名称
  team-name: China Fire 2019 Committee #团队名称
  text:
  #---------邮箱发送导出图片--------------------
mailExp:
  from: committee@cfpa.cn  #发送邮箱
  subject: 第十八届中国国际消防展展商系统s%展馆导出图片 #邮箱标题
  time: 1小时            #时效
  system-name: 第十八届中国国际消防展展商系统  #系统名称
  team-name: 第十八届中国国际消防展组委会 #团队名称
  text:
  pic-name: s%展馆图片.png
#---------产品图片--------------------------
qycpjs:
  savePath: D://xfxh//upload//
  fileServerUrl: http://10.119.119.222:80
  vueServerUrl: http://10.119.119.222:80
#------------------------------------------------------------
#spring
spring:
  profiles:
    active: dev
  druid:
    #配置druid连接池
    datasource:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  mail:
    default-encoding: UTF-8
    host: smtp.ym.163.com #邮箱SMTP服务器  QQ邮箱smtp.qq.com  网易个人免费smtp.163.com 网易企业邮箱smtp.ym.163.com
    port: 25 #端口
    protocol: smtp
    username: committee@cfpa.cn
    password: fe123456   #---------- QQ邮箱生成授权码： QQ邮箱-设置-账户- POP3/IMAP/SMTP/Exchange/CardDAV/CalDAV服务 - 开启服务
  mybatis:
    mapperLocations: classpath:mapper/*-mapper.xml
    typeAliasesPackage: com.syfri.userservice
    basePackage: com.syfri.userservice.dao
    configuration:
      cacheEnabled: false
      lazyLoadingEnabled: false
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: 10.119.119.233
    port: 6379
    expire: 1800
    timeout: 0
  http:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB

#------------------------------------------------------------
#pagehelper分页插件设置
pagehelper:
  helper-dialect: oracle
  reasonable: true
  support-methods-arguments: true
  row-bounds-with-count: true
  auto-dialect: true
#------------------------------------------------------------
logging:
  level.root: info
  level.com.syfri: debug
  path: logs/
  file: userservice.log
  ##########################################################
  ###################  开发环境的profile  ###################
  ##########################################################
---
spring:
  profiles: dev
  druid:
    #配置druid连接池
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: oracle.jdbc.OracleDriver
      url: jdbc:oracle:thin:@127.0.0.1:1521/XFXHDB
#      url: jdbc:oracle:thin:@localhost:1521/orcl
      username: XFXHZH
      password: XFXHZH
#      url: jdbc:oracle:thin:@localhost:1521/orcl
#      username: rliu
#      password: RLIU

  ##########################################################
  ###################  正式环境的profile  ###################
  ##########################################################
---
spring:
  profiles: produce
  druid:
    #配置druid连接池
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: oracle.jdbc.OracleDriver
      url: jdbc:oracle:thin:@10.119.123.25:1521/XFXHDB
      username: XFXHZH
      password: XFXHZH

#------------------------------------------------------------
#swagger:
#  title: springboot
#  description: springboot swagger
#  version: 1.0
#  license: 111
#  license-url: https://www.apache.org/licenses/LICENSE-2.0.html
#  terms-of-service-url: https://github.com/dyc87112/spring-boot-starter-swagger
#  contact:
#    email: xxx@syfri.cn
#    name: lx
#    url: http://blog.didispace.com
#  base-package: com.syfri
#------------------------------------------------------------